sudo: required
services:
    - docker
before_install:
    - docker build -t gauravshindolkar/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run gauravshindolkar/react-test npm test -- --coverage
    
after_success:
    - docker build -t gauravshindolkar/multi-client ./client
    - docker build -t gauravshindolkar/multi-nginx ./nginx
    - docker build -t gauravshindolkar/multi-server ./server
    - docker build -t gauravshindolkar/multi-worker ./worker
    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them to docker hub
    - docker push gauravshindolkar/multi-client
    - docker push gauravshindolkar/multi-nginx
    - docker push gauravshindolkar/multi-server
    - docker push gauravshindolkar/multi-worker
    
deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-554693105445
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY